GoodQRma/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GoodQRma.Models;
using Microsoft.AspNet.Identity;
using PagedList.Mvc;
using PagedList;
using System.Net.Mail;


namespace GoodQRma.Controllers
{

    [Authorize]
    public class EventController : Controller
    {

        ApplicationDbContext db = new ApplicationDbContext();


        // GET: Event
        [AllowAnonymous]

        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.currentSort = sortOrder;
            ViewBag.NameSortParm = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var events = from v in db.Events
                         select v;

            if (!string.IsNullOrEmpty(searchString))
            {
                events = events.Where(v => v.eventType.Contains(searchString));

            }

            switch (sortOrder)
            {
                case "name_desc":
                    events = events.OrderByDescending(v => v.eventType);
                    break;
                case "Date":
                    events = events.OrderBy(v => v.eventDate);
                    break;
                case "date_desc":
                    events = events.OrderByDescending(v => v.eventDate);
                    break;
                default:
                    events = events.OrderBy(v => v.eventType);
                    break;

            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);


            return View(events.ToPagedList(pageNumber, pageSize));
        }

        // GET: Event/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);

            db.Events.Include(s => s.Files).SingleOrDefault(s => s.eventID == id);

            if (@event == null)
            {
                return HttpNotFound();
            }

            if (User.Identity.IsAuthenticated && !User.IsInRole("Admin"))
            {
                string currentUserID = User.Identity.GetUserId();
                var currentUser = db.Users.Single(u => u.Id == currentUserID);

                ViewBag.Here = currentUser.Events.Contains(@event) ? "Leave" : "Volunteer!";
            }
            else
                ViewBag.Here = "Volunteer!";

            return View(@event);
        }

        //POST Details
        [HttpPost]
        [ActionName("Details")]
        public ActionResult ChangeAttendance(int? id)
        {
            if (User.Identity.IsAuthenticated)
            {
                //Get current user's id
                var idid = User.Identity.GetUserId();

                //Find current event and current user
                ApplicationUser user = db.Users.Single(u => u.Id == idid);
                Event @event = db.Events.Single(e => e.eventID == id);

                //SMTP Email set up
                MailMessage msg = new MailMessage("goodqrma@gmail.com", @user.Email);
                SmtpClient client = new SmtpClient("smtp.gmail.com", 587);
                client.EnableSsl = true;
                client.DeliveryMethod = SmtpDeliveryMethod.Network;
                client.UseDefaultCredentials = false;
                client.Credentials = new NetworkCredential("goodqrma@gmail.com", "4goodqrma");



                if (user.Events.Contains(@event))
                {
                    //Add user as attending event
                    @event.Users.Remove(user);
                    user.Events.Remove(@event);

                    //Change button to join event
                    ViewBag.Here = "Volunteer!";

                    //Save database changes
                    db.SaveChanges();

                    //Send confirmation email
                    msg.Subject = @event.name + " Confirmation";
                    msg.Body = "Hello, " + user.Name + "\n\nYou are no longer attending " + @event.name + " on " + @event.eventDate + " at " + @event.eventTime + "\n\nThank You, \nGoodQRma";
                    client.Send(msg);
                }
                else
                {
                    //Add user as attending event
                    @event.Users.Add(user);
                    user.Events.Add(@event);

                    //Change button to leave event
                    ViewBag.Here = "Opt Out";

                    //Save database changes
                    db.SaveChanges();

                    //Send confirmation email
                    msg.Subject = @event.name + " Confirmation";
                    msg.Body = "Hello, " + user.Name + "\n\nYou are confirmed to attend " + @event.name + " on " + @event.eventDate + " at " + @event.eventTime + "\n\nThank You, \nGoodQRma";
                    client.Send(msg);
                }

                return View(@event);
            }
            else
                return View("Login", "Account");

        }

        // GET: Event/Create
        [Authorize(Roles = "Member")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Event/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "eventID,image,name,description,eventType,eventDate,eventTime,numVolunteersNeeded,address1,city,state,zipCode,country,contact,phone,eventURL")] Event @event, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {


                //Ties the logged in USER to the created EVENT
                @event.userID = User.Identity.GetUserId();


                if (upload != null && upload.ContentLength > 0)
                {
                    var avatar = new File
                    {
                        FileName = System.IO.Path.GetFileName(upload.FileName),
                        FileType = FileType.Avatar,
                        ContentType = upload.ContentType
                    };
                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        avatar.Content = reader.ReadBytes(upload.ContentLength);
                    }
                    @event.Files = new List<File> { avatar };
                }

                db.Events.Add(@event);
                db.SaveChanges();





                return RedirectToAction("Index");
            }

            return View(@event);
        }

        // GET: Event/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Event/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "eventID,userID,image,name,description,eventType,eventDate,eventTime,numVolunteersNeeded,address1,city,state,zipCode,country,contact,phone,eventURL")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(@event);
        }


        //[Authorize(Roles = "Member")]
        public ActionResult EventPoster(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }



            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }


            return View("EventPoster", "_Layout2", @event);
        }


        // GET: Event/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Event/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event @event = db.Events.Find(id);

            if (@event.userID == User.Identity.GetUserId() || User.IsInRole("Admin"))
            {
                db.Events.Remove(@event);
                db.SaveChanges();
            }
            
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GoodQRma/Controllers/UserViewModelsController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using GoodQRma.Models;
using System.Net;
using System.Data.Entity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Collections.Generic;
using System.Web.ModelBinding;

namespace GoodQRma.Controllers
{


     [Authorize]
    public class UserViewModelsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: UserViewModels


          [Authorize(Roles = "Admin")]
            public ActionResult Index()
            {
                var allusers = db.Users.ToList();
                return View (allusers);
     
            }


        [Authorize(Roles = "Admin")]
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserViewModel userViewModel = db.UserViewModels.Find(id);
            if (userViewModel == null)
            {
                return HttpNotFound();
            }
            return View(userViewModel);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserViewModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserViewModelId,Username,Roles")] UserViewModel userViewModel)
        {
            if (ModelState.IsValid)
            {
                db.UserViewModels.Add(userViewModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userViewModel);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserViewModel userViewModel = db.UserViewModels.Find(id);
            if (userViewModel == null)
            {
                return HttpNotFound();
            }
            return View(userViewModel);
        }

        // POST: UserViewModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "UserViewModelId,Username,Roles")] UserViewModel userViewModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userViewModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userViewModel);
        }

        // GET: UserViewModels/Delete/5
          [Authorize(Roles = "Admin")]
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

             

            UserViewModel userViewModel = db.UserViewModels.Find(id);
            if (userViewModel == null)
            {
                return HttpNotFound();
            }
            return View(userViewModel);
        }



         







        // POST: UserViewModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(string id)
        {
            UserViewModel userViewModel = db.UserViewModels.Find(id);
            db.UserViewModels.Remove(userViewModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public List<ApplicationUser> model { get; set; }
    }
}

GoodQRma/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - goodQRma</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>
                        <span>
                            <a href="@Url.Action("Index", "Home")" class="pull-left">
                                <img src="~/Images/GoodQRma_logo.png" title="title" alt="additional title" />
                            </a>
                        </span>
                    </li>


                </ul>

                <ul class="nav navbar-nav">


                    <li>@Html.ActionLink("View Event", "Index", "Event") </li>
                    <li>@Html.ActionLink("Create Event", "Create", "Event")</li>

                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    <li>@Html.ActionLink("My Profile", "UserProfile", "Account")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <center>
                    <p>&copy; @DateTime.Now.Year - GoodQRma.com</p>
                    <img src="~/Images/GoodQRma_logo2.png" />
                </center>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/jqueryui")
        @Styles.Render("~/Content/themes/base/css")
        @RenderSection("scripts", required: false)
</body>
</html>

GoodQRma/Views/Shared/_Layout2.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_Layout2</title>
</head>
<body>
    <center>






        <div>
        </div>

        <div class="container body-content">
            @RenderBody()
            <hr />

            <center>
                <p>&copy; @DateTime.Now.Year - GoodQRma.com</p>
                <img src="~/Images/GoodQRma_logo2.png" />
            </center>


        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/jqueryui")
        @Styles.Render("~/Content/themes/base/css")
        @RenderSection("scripts", required: false)


    </center>

        </body>
</html>

GoodQRma/Views/Shared/_LayoutADMIN.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - goodQRma</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>




            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>
                        <span>
                            <a href="@Url.Action("Index", "Home")" class="pull-left">
                                <img src="~/Images/GoodQRma_logo.png" title="title" alt="additional title" />
                            </a>
                        </span>
                    </li>


                </ul>

                <ul class="nav navbar-nav">
                                        
                    <li>@Html.ActionLink("ADMIN User", "Index", "UserViewModels")</li>
                    <li>@Html.ActionLink("ADMIN Event", "Index", "Admin")</li>




                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <center>
                <p>&copy; @DateTime.Now.Year - GoodQRma.com</p>
                <img src="~/Images/GoodQRma_logo2.png" />
            </center>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/themes/base/css")
    @RenderSection("scripts", required: false)
</body>
</html>

GoodQRma/Views/Shared/_LayoutHOME.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - goodQRma</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    



                </button>




            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>
                        <span>
                        <a href="@Url.Action("Index", "Home")" class="pull-left">
                            <img src="~/Images/GoodQRma_logo.png" title="title" alt="additional title" />
                        </a>
                        </span>
                    </li>

                   
                </ul>
                
                <ul class="nav navbar-nav">
                                       

                    <li>@Html.ActionLink("View Event", "Index", "Event") </li>
                    <li>@Html.ActionLink("Create Event", "Create", "Event")</li>

                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    <li>@Html.ActionLink("My Profile", "UserProfile", "Account")</li>


                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

   
               




        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <center>
                    <p>&copy; @DateTime.Now.Year - GoodQRma.com</p>
                    <img src="~/Images/GoodQRma_logo2.png" />
                </center>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/jqueryui")
        @Styles.Render("~/Content/themes/base/css")
        @RenderSection("scripts", required: false)
</body>
</html>